# Generated by Django 2.1.7 on 2021-04-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_address_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='Japan', max_length=120),
        ),
    ]
