# Generated by Django 2.0.1 on 2019-07-06 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20190701_2319'),
        ('otherdetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherdetails',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product_description'),
        ),
    ]
