# Generated by Django 2.0.1 on 2019-06-23 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20190623_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='days',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='size',
        ),
    ]
