# Generated by Django 2.0.1 on 2020-03-21 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_view_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='view_count',
            options={'ordering': ['-views']},
        ),
    ]
