# Generated by Django 2.0.1 on 2020-02-09 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_coupon'),
        ('billing', '0007_auto_20190620_0032'),
        ('notification', '0004_auto_20200208_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier_Order_Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('message', models.TextField()),
                ('viewed', models.BooleanField(default=False)),
                ('status', models.CharField(default='created', max_length=120)),
                ('billing_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.BillingProfile')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
    ]
