# Generated by Django 2.1.7 on 2021-02-23 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0012_cartitem_order_confirmed'),
        ('products', '0054_auto_20200901_1757'),
        ('notification', '0005_auto_20200826_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Order_Status_Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.BooleanField(default=False)),
                ('seen', models.BooleanField(default=False)),
                ('order_confirmed', models.CharField(default='none', max_length=50)),
                ('supplier_cancellation', models.BooleanField(default=False)),
                ('status', models.CharField(default='created', max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.Cart')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product_description')),
            ],
        ),
    ]
