# Generated by Django 2.0.1 on 2020-02-09 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_supplier_order_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier_order_notification',
            old_name='order',
            new_name='order_id',
        ),
    ]
