# Generated by Django 2.1.7 on 2021-04-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_user_order_status_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_order_status_notification',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='user_order_status_notification',
            name='product',
        ),
        migrations.AddField(
            model_name='order_current_status',
            name='order_confirmed',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='order_current_status',
            name='supplier_cancellation',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='User_Order_Status_Notification',
        ),
    ]
