# Generated by Django 2.0.1 on 2020-03-03 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0010_auto_20200226_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='low_quantity_notification',
            name='product',
        ),
        migrations.DeleteModel(
            name='Low_Quantity_Notification',
        ),
    ]
