# Generated by Django 2.0.1 on 2020-07-26 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0028_auto_20200724_2248'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0053_auto_20200726_1803'),
        ('notification', '0011_auto_20200304_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_current_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.BooleanField(default=False)),
                ('supplier_viewed', models.BooleanField(default=False)),
                ('seen', models.BooleanField(default=False)),
                ('supplier_seen', models.BooleanField(default=False)),
                ('status', models.CharField(default='paid', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.Cart')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product_description')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='supplier_order_notification',
            name='billing_profile',
        ),
        migrations.RemoveField(
            model_name='supplier_order_notification',
            name='message',
        ),
        migrations.RemoveField(
            model_name='supplier_order_notification',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='supplier_order_notification',
            name='title',
        ),
        migrations.AddField(
            model_name='notification',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order_notification',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.Cart'),
        ),
        migrations.AddField(
            model_name='order_notification',
            name='order_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='order_notification',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order_notification',
            name='status',
            field=models.CharField(default='created', max_length=120),
        ),
        migrations.AddField(
            model_name='supplier_order_notification',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product_description'),
        ),
        migrations.AddField(
            model_name='supplier_order_notification',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
