# Generated by Django 2.0.1 on 2020-05-17 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0012_auto_20200517_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_current_status',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.Cart'),
        ),
        migrations.AlterField(
            model_name='order_current_status',
            name='status',
            field=models.CharField(default='paid', max_length=50),
        ),
        migrations.AlterField(
            model_name='order_notification',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.Cart'),
        ),
        migrations.AlterField(
            model_name='supplier_order_notification',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.Cart'),
        ),
    ]
