# Generated by Django 2.0.1 on 2020-05-17 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0013_auto_20200517_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_current_status',
            name='variations',
        ),
    ]
