# Generated by Django 2.0.1 on 2020-05-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0014_remove_order_current_status_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order_current_status',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order_current_status',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order_notification',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplier_order_notification',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
