# Generated by Django 2.0.1 on 2020-05-18 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0015_auto_20200518_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_current_status',
            name='supplier_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order_current_status',
            name='supplier_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
