# Generated by Django 2.0.1 on 2020-05-19 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0063_auto_20200512_1809'),
        ('notification', '0017_auto_20200519_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier_order_notification',
            name='billing_profile',
        ),
        migrations.RemoveField(
            model_name='supplier_order_notification',
            name='message',
        ),
        migrations.RemoveField(
            model_name='supplier_order_notification',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='supplier_order_notification',
            name='title',
        ),
        migrations.AddField(
            model_name='supplier_order_notification',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product_description'),
        ),
    ]
