# Generated by Django 2.0.1 on 2019-06-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default=1, max_length=10),
        ),
    ]
