# Generated by Django 2.0.1 on 2019-07-05 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_otherdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherdetails',
            name='product',
        ),
    ]
