# Generated by Django 2.0.1 on 2020-08-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_auto_20200826_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
