# Generated by Django 2.0.1 on 2019-07-05 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otherdetails', '0001_initial'),
        ('carts', '0007_remove_otherdetails_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherdetails',
            name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='other',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='otherdetails.OtherDetails'),
        ),
        migrations.DeleteModel(
            name='OtherDetails',
        ),
    ]
