# Generated by Django 2.0.1 on 2019-07-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otherdetails', '0001_initial'),
        ('carts', '0008_auto_20190705_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='other',
        ),
        migrations.AddField(
            model_name='cart',
            name='other',
            field=models.ManyToManyField(blank=True, null=True, to='otherdetails.OtherDetails'),
        ),
    ]
