# Generated by Django 2.0.1 on 2021-02-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_auto_20210217_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmessage',
            name='order_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='transactionmessage',
            name='cart_id',
            field=models.IntegerField(),
        ),
    ]
