# Generated by Django 2.0.1 on 2019-07-05 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_auto_20190705_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='other',
        ),
    ]
