# Generated by Django 2.0.1 on 2019-07-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otherdetails', '0002_otherdetails_product'),
        ('carts', '0010_remove_cart_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='other',
            field=models.ManyToManyField(blank=True, null=True, to='otherdetails.OtherDetails'),
        ),
    ]
