# Generated by Django 2.0.1 on 2019-07-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0011_cart_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='other',
            field=models.ManyToManyField(blank=True, to='otherdetails.OtherDetails'),
        ),
    ]
