# Generated by Django 2.0.1 on 2021-02-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0011_cartitem_supplier_cancellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='order_confirmed',
            field=models.CharField(choices=[('none', 'none'), ('confirmed', 'confirmed'), ('rejected', 'rejected')], default='none', max_length=120),
        ),
    ]
