# Generated by Django 2.1.7 on 2021-04-12 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0012_cartitem_order_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionmessage',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
