# Generated by Django 2.1.7 on 2021-04-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0013_auto_20210412_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='return_initiated',
            field=models.BooleanField(default=False),
        ),
    ]
