# Generated by Django 2.0.1 on 2020-01-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0018_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='other',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
