# Generated by Django 2.0.1 on 2020-01-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0019_auto_20200122_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
    ]
