# Generated by Django 2.0.1 on 2020-02-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0020_coupon_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='days',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
