# Generated by Django 2.0.1 on 2020-03-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0022_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='refund_granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='refund_requested',
            field=models.BooleanField(default=False),
        ),
    ]
