# Generated by Django 2.0.1 on 2020-05-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0024_cart_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.CharField(default='created', max_length=50),
        ),
    ]
