# Generated by Django 2.0.1 on 2020-05-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0026_auto_20200508_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shipping_total',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=50),
        ),
    ]
