# Generated by Django 2.0.1 on 2020-07-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0028_auto_20200724_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='quantity',
            field=models.IntegerField(default=-1),
        ),
    ]
