# Generated by Django 2.0.1 on 2019-05-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_description_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_description',
            name='quantity',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
