# Generated by Django 2.0.1 on 2019-05-26 12:45

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_description_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_description',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path),
        ),
    ]
