# Generated by Django 2.0.1 on 2019-05-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190526_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_description',
            old_name='cost',
            new_name='cost_per_day',
        ),
        migrations.AddField(
            model_name='product_description',
            name='days',
            field=models.IntegerField(null=True),
        ),
    ]
