# Generated by Django 2.0.1 on 2019-06-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_description_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_description',
            name='catogary',
            field=models.CharField(default='clothing', max_length=100),
        ),
    ]
