# Generated by Django 2.0.1 on 2019-06-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_description_catogary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_description',
            name='catogary',
            field=models.CharField(choices=[('Clothing', 'Clothing'), ('Accessories', 'Accessories'), ('Books + novels', 'Books + novels'), ('Instruments', 'Instruments')], default=1, max_length=50),
        ),
    ]
