# Generated by Django 2.0.1 on 2019-06-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20190621_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_description',
            name='days',
        ),
        migrations.RemoveField(
            model_name='product_description',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product_description',
            name='size',
        ),
    ]
