# Generated by Django 2.0.1 on 2019-06-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shop_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Address_Line1', models.CharField(blank=True, max_length=555, null=True)),
                ('Address_Line2', models.CharField(blank=True, max_length=100, null=True)),
                ('Postal_code', models.IntegerField(blank=True, null=True)),
                ('City', models.CharField(blank=True, max_length=55, null=True)),
                ('Mobile_number', models.IntegerField(blank=True, null=True)),
                ('Shop_registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
