# Generated by Django 2.0.1 on 2019-06-27 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190627_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='Shop_name',
        ),
    ]
