# Generated by Django 2.0.1 on 2019-07-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190627_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_supplier',
            field=models.BooleanField(default=True),
        ),
    ]
