# Generated by Django 2.0.1 on 2019-07-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190708_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='bank_account_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
