# Generated by Django 2.0.1 on 2019-07-25 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_supplier_bank_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='email',
        ),
    ]
