# Generated by Django 2.0.1 on 2020-04-21 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_emailactivation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Account_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_holder_name', models.CharField(max_length=100)),
                ('Account_number', models.PositiveIntegerField()),
                ('IFSC_code', models.CharField(max_length=20)),
                ('Account_type', models.CharField(choices=[('Overdraft Account', 'Overdraft Account'), ('Saving Account', 'Saving Account'), ('Current Account', 'Current Account')], max_length=25)),
                ('email', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='Shop_registration_number',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='bank_account_number',
        ),
        migrations.AddField(
            model_name='supplier',
            name='Country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='Nick_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='Mobile_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='Shop_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
