# Generated by Django 2.0.1 on 2020-04-21 16:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200421_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_account_detail',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bank_account_detail',
            name='supplier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Supplier'),
        ),
        migrations.AddField(
            model_name='bank_account_detail',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank_account_detail',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
