# Generated by Django 2.0.1 on 2020-07-26 11:24

import accounts.models
from django.db import migrations
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200726_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=accounts.models.upload_image_path, validators=[stdimage.validators.MaxSizeValidator(1050, 1050)]),
        ),
    ]
