# Generated by Django 2.0.1 on 2020-07-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20200726_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_account_detail',
            name='Account_number',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='Mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
