# Generated by Django 2.0.1 on 2020-04-23 17:15

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20200421_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='receive_message_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_image_path, validators=[accounts.models.validate_image]),
        ),
        migrations.AddField(
            model_name='user',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
