# Generated by Django 2.0.1 on 2020-04-25 17:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200423_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_account_detail',
            name='Account_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999999999)]),
        ),
    ]
