# Generated by Django 2.0.1 on 2020-06-27 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20200627_1624'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('email', 'Shop_name')},
        ),
    ]
