# Generated by Django 2.0.1 on 2020-07-24 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20200627_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='Mobile_number',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999999)]),
        ),
    ]
