# Generated by Django 2.0.1 on 2019-06-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='catogary',
            field=models.CharField(default='products', max_length=100),
        ),
    ]
