# Generated by Django 2.0.1 on 2019-06-10 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tag_catogary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='catogary',
        ),
    ]
