# Generated by Django 2.0.1 on 2020-03-08 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0052_auto_20200223_1757'),
        ('tags', '0003_remove_tag_catogary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='product_name',
            new_name='tag_name',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='products',
        ),
        migrations.AddField(
            model_name='tag',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product_description'),
        ),
    ]
