# Generated by Django 2.0.1 on 2020-03-08 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_auto_20200308_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='product',
            new_name='product_name',
        ),
    ]
