# Generated by Django 2.0.1 on 2019-06-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190609_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.CharField(blank=True, default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default=1, max_length=10),
        ),
    ]
