# Generated by Django 2.0.1 on 2019-06-23 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_details_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order_details',
        ),
    ]
