# Generated by Django 2.0.1 on 2019-07-02 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20190701_2319'),
        ('orders', '0009_auto_20190626_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product_description')),
            ],
        ),
    ]
