# Generated by Django 2.0.1 on 2019-07-04 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_supplierorders_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierorders',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='supplierorders',
            name='products',
        ),
        migrations.RemoveField(
            model_name='supplierorders',
            name='user',
        ),
        migrations.DeleteModel(
            name='SupplierOrders',
        ),
    ]
