# Generated by Django 2.0.1 on 2019-08-13 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_refund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='email',
        ),
        migrations.AddField(
            model_name='refund',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
