# Generated by Django 2.0.1 on 2020-01-22 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0019_auto_20200122_1509'),
        ('orders', '0015_auto_20190813_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.Coupon'),
        ),
    ]
