# Generated by Django 2.0.1 on 2020-09-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20200826_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancel_item',
            name='cartitem_id',
            field=models.IntegerField(default=0),
        ),
    ]
