# Generated by Django 2.0.1 on 2020-03-03 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0052_auto_20200223_1757'),
        ('orders', '0016_order_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Low_Quantity_Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('viewed', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product_description')),
            ],
        ),
    ]
