# Generated by Django 2.0.1 on 2020-03-22 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_refund_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
    ]
