# Generated by Django 2.0.1 on 2020-07-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20200726_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='low_quantity_notification',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
