# Generated by Django 2.0.1 on 2020-05-19 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20200508_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='low_quantity_notification',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
