# Generated by Django 2.0.1 on 2020-05-25 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_low_quantity_notification_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_total',
        ),
    ]
