# Generated by Django 2.0.1 on 2019-05-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_description',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
