# Generated by Django 2.0.1 on 2019-05-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_description_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_description',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='products/'),
        ),
    ]
