# Generated by Django 2.0.1 on 2019-05-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190527_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_description',
            name='featured',
            field=models.BooleanField(default=True),
        ),
    ]
