# Generated by Django 2.0.1 on 2019-05-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20190527_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_description',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
