# Generated by Django 2.0.1 on 2019-05-29 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20190527_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_description',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
