# Generated by Django 2.0.1 on 2019-06-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_description',
            name='size',
            field=models.CharField(choices=[('None', 'None'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default=1, max_length=10),
        ),
    ]
