# Generated by Django 2.0.1 on 2019-06-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_description_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_description',
            name='quantity',
            field=models.CharField(default=1, max_length=10, null=True),
        ),
    ]
