# Generated by Django 2.0.1 on 2019-06-28 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0017_auto_20190621_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_description',
            old_name='catogary',
            new_name='categary',
        ),
        migrations.AddField(
            model_name='product_description',
            name='email',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_description',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product_description',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'S'), (2, 'M'), (3, 'L'), (4, 'XL'), (5, 'Not applicable')], default=5, max_length=9),
        ),
        migrations.AddField(
            model_name='product_description',
            name='sub_categary',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
