# Generated by Django 2.0.1 on 2019-06-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20190628_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_description',
            name='brand',
            field=models.CharField(default=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product_description',
            name='email',
            field=models.EmailField(default=True, max_length=254, null=True),
        ),
    ]
