# Generated by Django 2.0.1 on 2019-06-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20190629_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_description',
            name='email',
            field=models.EmailField(default='accounts.User', max_length=254, null=True),
        ),
    ]
