# Generated by Django 2.0.1 on 2019-06-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20190629_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_description',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
