# Generated by Django 2.0.1 on 2019-06-29 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20190629_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_description',
            old_name='email',
            new_name='registered_email',
        ),
    ]
