# Generated by Django 2.0.1 on 2019-07-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_product_description_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_description',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
