# Generated by Django 2.0.1 on 2019-08-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20190804_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_description',
            name='brand',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
