# Generated by Django 2.0.1 on 2019-08-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20190804_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier_review',
            name='customer',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
