# Generated by Django 2.0.1 on 2020-01-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20190804_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_description',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
