# Generated by Django 2.0.1 on 2020-01-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_auto_20200111_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
