# Generated by Django 2.0.1 on 2020-01-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_variation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
