# Generated by Django 2.0.1 on 2020-01-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_auto_20200120_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_description',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
