# Generated by Django 2.0.1 on 2020-02-01 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_description',
            name='categary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Category'),
        ),
    ]
