# Generated by Django 2.0.1 on 2020-02-03 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_auto_20200202_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_description',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product_description',
            name='registered_email',
        ),
        migrations.RemoveField(
            model_name='product_description',
            name='size',
        ),
    ]
