# Generated by Django 2.0.1 on 2020-02-15 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_auto_20200215_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='product',
            new_name='product_name',
        ),
    ]
