# Generated by Django 2.0.1 on 2020-02-16 11:38

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_auto_20200216_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=products.models.upload_image_path),
        ),
    ]
