# Generated by Django 2.0.1 on 2020-02-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_auto_20200216_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='variations',
        ),
        migrations.AddField(
            model_name='quantity',
            name='color',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='quantity',
            name='size',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
