# Generated by Django 2.0.1 on 2020-02-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_auto_20200217_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='color',
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='size',
        ),
        migrations.AddField(
            model_name='quantity',
            name='variations',
            field=models.ManyToManyField(blank=True, to='products.Variation'),
        ),
    ]
