# Generated by Django 2.0.1 on 2020-03-13 00:06

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0052_auto_20200223_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_description',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='product_description',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path, validators=[products.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=products.models.upload_image_path, validators=[products.models.validate_image]),
        ),
    ]
