# Generated by Django 2.0.1 on 2020-09-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0053_auto_20200726_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_refund',
            name='cartitem_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_review',
            name='cartitem_id',
            field=models.IntegerField(default=0),
        ),
    ]
