# Generated by Django 2.1.7 on 2021-04-19 12:01

from django.db import migrations, models
import products.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0055_rentalperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path, validators=[stdimage.validators.MaxSizeValidator(1050, 1050)]),
        ),
        migrations.AlterField(
            model_name='category',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
