# Generated by Django 2.0.1 on 2020-04-21 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0055_auto_20200414_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_description',
            options={},
        ),
    ]
