# Generated by Django 2.0.1 on 2020-04-25 17:30

from django.db import migrations, models
import django.utils.timezone
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0056_auto_20200421_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_description',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=products.models.upload_image_path, validators=[products.models.validate_image]),
            preserve_default=False,
        ),
    ]
