# Generated by Django 2.0.1 on 2020-05-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0058_auto_20200502_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_description',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
