# Generated by Django 2.1.7 on 2021-05-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0058_sub_sub_category_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='variations',
            field=models.ManyToManyField(blank=True, to='products.Variation'),
        ),
    ]
