# Generated by Django 2.0.1 on 2020-05-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0059_product_description_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_description',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='user_review',
            name='rating',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=5),
        ),
    ]
