# Generated by Django 2.0.1 on 2020-05-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0060_auto_20200510_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_description',
            name='city',
            field=models.CharField(choices=[(1, 'Tokyo'), (2, 'Osaka'), (3, 'Kyoto')], default=1, max_length=30),
        ),
    ]
