# Generated by Django 2.0.1 on 2020-05-11 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0061_product_description_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_description',
            old_name='city',
            new_name='Current_City',
        ),
        migrations.RenameField(
            model_name='product_description',
            old_name='categary',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product_description',
            old_name='sub_categary',
            new_name='sub_category',
        ),
        migrations.RenameField(
            model_name='product_description',
            old_name='sub_sub_categary',
            new_name='sub_sub_category',
        ),
    ]
