# Generated by Django 2.0.1 on 2020-05-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0062_auto_20200511_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_description',
            name='Current_City',
            field=models.CharField(default='Tokyo', max_length=30),
        ),
    ]
